[package]
name = "trajectory"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow = { workspace = true }
parquet = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
